# Cloud Build configuration for Frontend Service

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:$SHORT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:latest'
      - './frontend'
    dir: '.'

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend'
    waitFor: ['build-frontend-image']

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-frontend-service'
    args:
      - 'app'
      - 'deploy'
      - './frontend/app.yaml'
      - '--image-url=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:$SHORT_SHA'
      - '--quiet'
      - '--promote'
    waitFor: ['push-frontend-image']

# Use CI/CD service account
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/app-engine-cicd@$PROJECT_ID.iam.gserviceaccount.com'

# Timeout
timeout: '1200s'

# Machine type
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Tags for organization
tags: ['frontend', 'microservices', 'docker', 'nginx']

# Substitutions
substitutions:
  _REGION: us-central1
  _REPO: app-containers
