runtime: custom
env: flex

service: backend

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  instance_tag: backend-service

env_variables:
  ENVIRONMENT: dev
  LOG_LEVEL: INFO
  GCP_PROJECT_ID: semiotic-runner-483110-p1

liveness_check:
  path: /api/health
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300

readiness_check:
  path: /api/health
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
